# 基础设置
# 真机: UUID。如: 10ACAU0MQX001UX (一般是5037端口，其他也行，能连上手机就行)
# 夜神模拟器: 127.0.0.1:62025
# mumu模拟器: 127.0.0.1:7555
client_url: 10ACAU0MQX001UX # 设备连接UUID或url
log_output: false # 是否将日志写入文件

# 运行设置
shutdown_when_finish: false # 运行完毕后是否关机
# 定时运行，不定时则输入false，定时则输入时间，格式%H:%M(24小时)，如18:13，程序在这个时间后执行模块(需要加引号)，若设置的定时时间小于当前时间，则不定时直接开始
start_timer: false
rerun_if_fail: 0 # 运行失败后重新运行次数
run_model_list: # 运行的模块列表，注意先后顺序
    - 任务
    - 工会之家
    - 商店
    - 探索
    - 调查
    - 竞技场
    - 地下城
    - 任务
    - 礼物

# 插件模块设置
run_plugins: false # 运行其他插件模块(开启后，不会运行主要模块)
plugins_run_times: 1 # 插件模块运行次数
# 需要运行的插件模块，以下是可运行的插件
# 信赖度
plugins_model: 信赖度
